---
postgresql:
  fullnameOverride: "rawdatadb"
  image:
    pullPolicy: Always
  auth:
    database: &psqlDatabase "rawdata"
    username: &psqlUsername "rawdata_user"
    password: &psqlPassword "rawdata_pass"

  persistence:
    enabled: false

  # initdbUsername: *psqlUsername
  # initdbPassword: *psqlPassword

credentials:
  cloud:
    accessKey: &cloudKey zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    secretKey: &cloudSecret someSecret
  apiwrapper:
    username: &apiwrapperUser user
    password: &apiwrapperPass pass
  api:
    username: &apiUser user
    password: &apiPass pass
  rawdata:
    username: &rawdataUser rawdata_user
    password: &rawdataPass rawdata_pass
  healthindicator:
    username: &hiUser healthindicator_user
    password: &hiPass healthindicator_pass

hiapp:
  ingress:
    enabled: true
    className: ""
    tls: true
    certManager:
      issuer: ""
      clusterIssuer: ""

    annotations: {}
    hostname: "bmw-hiapp.dev.demo.catena-x.net"
    secret: tls-secret

  server:
    port: 25553

  connection:
    endpoints:
      default:
        port: 25553
        path: /
        ingress: True

  credentials:
    cloud:
      accessKey: *cloudKey
      secretKey: *cloudSecret
    apiwrapper:
      username: *apiwrapperUser
      password: *apiwrapperPass
    api:
      username: *apiUser
      password: *apiPass
    rawdata:
      username: *rawdataUser
      password: *rawdataPass
    healthindicator:
      username: *hiUser
      password: *hiPass

provider:
  ingress:
    enabled: true
    className: ""
    tls: true
    certManager:
      issuer: ""
      clusterIssuer: ""

    annotations: {}
    hostname: "bmw-provider.dev.demo.catena-x.net"
    secret: tls-secret

  server:
    port: 25553

  connection:
    endpoints:
      default:
        port: 25553
        path: /
        ingress: True

  credentials:
    cloud:
      accessKey: *cloudKey
      secretKey: *cloudSecret
    apiwrapper:
      username: *apiwrapperUser
      password: *apiwrapperPass
    api:
      username: *apiUser
      password: *apiPass
    rawdata:
      username: *rawdataUser
      password: *rawdataPass
    healthindicator:
      username: *hiUser
      password: *hiPass

updater:
  ingress:
    enabled: true
    className: ""
    tls: true
    certManager:
      issuer: ""
      clusterIssuer: ""

    annotations: {}
    hostname: "bmw-updater.dev.demo.catena-x.net"
    secret: tls-secret

  server:
    port: 25553

  connection:
    endpoints:
      default:
        port: 25553
        path: /
        ingress: True

  credentials:
    cloud:
      accessKey: *cloudKey
      secretKey: *cloudSecret
    apiwrapper:
      username: *apiwrapperUser
      password: *apiwrapperPass
    api:
      username: *apiUser
      password: *apiPass
    rawdata:
      username: *rawdataUser
      password: *rawdataPass
    healthindicator:
      username: *hiUser
      password: *hiPass
